# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LabelEdit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LabelEdit(object):
    def setupUi(self, LabelEdit):
        LabelEdit.setObjectName("LabelEdit")
        LabelEdit.resize(649, 437)
        self.layoutWidget = QtWidgets.QWidget(LabelEdit)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labEdit = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.labEdit.setFont(font)
        self.labEdit.setObjectName("labEdit")
        self.verticalLayout_2.addWidget(self.labEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listLabNames = QtWidgets.QListWidget(self.layoutWidget)
        self.listLabNames.setObjectName("listLabNames")
        item = QtWidgets.QListWidgetItem()
        self.listLabNames.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listLabNames.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listLabNames.addItem(item)
        self.horizontalLayout_2.addWidget(self.listLabNames)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labLabName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labLabName.setFont(font)
        self.labLabName.setObjectName("labLabName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labLabName)
        self.txtLabName = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtLabName.setMinimumSize(QtCore.QSize(0, 26))
        self.txtLabName.setObjectName("txtLabName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtLabName)
        self.labLabFarbe = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labLabFarbe.setFont(font)
        self.labLabFarbe.setObjectName("labLabFarbe")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labLabFarbe)
        self.cmbLabFarbe = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbLabFarbe.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbLabFarbe.setObjectName("cmbLabFarbe")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbLabFarbe)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnLabAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLabAdd.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLabAdd.setFont(font)
        self.btnLabAdd.setObjectName("btnLabAdd")
        self.verticalLayout.addWidget(self.btnLabAdd)
        self.btnLabEdit = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLabEdit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLabEdit.setFont(font)
        self.btnLabEdit.setObjectName("btnLabEdit")
        self.verticalLayout.addWidget(self.btnLabEdit)
        self.btnLabDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLabDelete.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLabDelete.setFont(font)
        self.btnLabDelete.setObjectName("btnLabDelete")
        self.verticalLayout.addWidget(self.btnLabDelete)
        self.btnLabImport = QtWidgets.QPushButton(self.layoutWidget)
        self.btnLabImport.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnLabImport.setFont(font)
        self.btnLabImport.setObjectName("btnLabImport")
        self.verticalLayout.addWidget(self.btnLabImport)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnOk = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOk.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.btnApply = QtWidgets.QPushButton(self.layoutWidget)
        self.btnApply.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnApply.setFont(font)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout.addWidget(self.btnApply)
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(LabelEdit)
        QtCore.QMetaObject.connectSlotsByName(LabelEdit)

    def retranslateUi(self, LabelEdit):
        _translate = QtCore.QCoreApplication.translate
        LabelEdit.setWindowTitle(_translate("LabelEdit", "Label Editor"))
        self.labEdit.setText(_translate("LabelEdit", "Labels Bearbeiten"))
        __sortingEnabled = self.listLabNames.isSortingEnabled()
        self.listLabNames.setSortingEnabled(False)
        item = self.listLabNames.item(0)
        item.setText(_translate("LabelEdit", "Auto Hindernis 1 erkannt"))
        item = self.listLabNames.item(1)
        item.setText(_translate("LabelEdit", "Auto Hindernis 2 verpasst"))
        item = self.listLabNames.item(2)
        item.setText(_translate("LabelEdit", "Auto Hindernis 3 nicht erkannt"))
        self.listLabNames.setSortingEnabled(__sortingEnabled)
        self.labLabName.setText(_translate("LabelEdit", "LabelName"))
        self.labLabFarbe.setText(_translate("LabelEdit", "LabelFarbe"))
        self.btnLabAdd.setText(_translate("LabelEdit", "Hinzufügen"))
        self.btnLabEdit.setText(_translate("LabelEdit", "Bearbeiten"))
        self.btnLabDelete.setText(_translate("LabelEdit", "Löschen"))
        self.btnLabImport.setText(_translate("LabelEdit", "Import..."))
        self.btnOk.setText(_translate("LabelEdit", "Ok"))
        self.btnApply.setText(_translate("LabelEdit", "Übernehmen"))
        self.btnCancel.setText(_translate("LabelEdit", "Abbrechen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabelEdit = QtWidgets.QDialog()
    ui = Ui_LabelEdit()
    ui.setupUi(LabelEdit)
    LabelEdit.show()
    sys.exit(app.exec_())

